- name: Create Jenkins Jobs
  hosts: localhost
  roles:
    - jobs
  vars:
    folders:
      - { name: "expense-project"}
      - { name: "expense-project/CI-Jobs"}
      - { name: "expense-project/Infra-Jobs"}
    mb_jobs:
      - { name: "expense-backend", folder: "expense-project/CI-Jobs", repo: "https://github.com/raghudevopsb76/expense-backend"}
      - { name: "expense-frontend", folder: "expense-project/CI-Jobs", repo: "https://github.com/raghudevopsb76/expense-frontend"}
    sb_jobs:
      - { name: "expense-ansible", folder: "expense-project/Infra-Jobs", repo: "https://github.com/raghudevopsb76/expense-ansible"}
      - { name: "expense-terraform", folder: "expense-project/Infra-Jobs", repo: "https://github.com/raghudevopsb76/expense-terraform"}


